AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f58b397bc5c1f2e8 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
